version: '2.4'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-jcr:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./artifactory/:/artifactory_extra_conf/
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 30
      start_period: 40s
  
  jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8880"
      - "50000:50000"
    volumes:
      - ./jenkins_controller/casc.yaml:/usr/share/jenkins/ref/casc.yaml
    restart: always
  
  jenkins_agent:
    depends_on:
      - jenkins
    container_name: jenkins_agent
    build: jenkins_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa public_key
    restart: always
  
  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:9.2.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always
  
  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    restart: always

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium_hub
    environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always